[tool.poetry]
name = "doc-agent-api"
version = "0.1.0"
description = ""
authors = ["KauanIzidoro <cnttbussineskauan@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
uvicorn = "^0.34.0"
fastapi = "^0.115.6"

[tool.poetry.group.dev.dependencies]
ruff = "^0.9.2"
taskipy = "^1.14.1"

[tool.ruff]
line-length = 79
extende-exclude = ['model-output']

[tool.ruff.lint]
preview = true
select = ['I', 'F', 'E', 'W', 'PL', 'PT']



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
